apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pi4amzapv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pi4amzapv-go 
  name: pi4amzapv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pi4amzapv-go 
